export const ADD_ERROR = 'ADD_ERROR'
export const REMOVE_ERROR = 'REMOVE_ERROR'

export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const GET_QUESTIONS = 'GET_QUESTIONS'
export const GET_SINGLE_QUESTION = 'GET_SINGLE_QUESTION'